server:
    port: 8080
javax:
    sql:
        DataSource:
            pokemonDataSource:
                dataSourceClassName: org.h2.jdbcx.JdbcDataSource
                dataSource:
                    url: jdbc:h2:mem:pokemon;INIT=RUNSCRIPT FROM 'classpath:pokemon.ddl' 
                    user: sa
                    password: ""